In [2]:
# for fast array manipulation
import numpy as np
# for plotting
import matplotlib.pyplot as plt
# for numerical ODE integration
from scipy.integrate import odeint
# for nonlinear equations
from scipy.optimize import fsolve
from matplotlib.pyplot import cm
# needed to calculate (complex) squareroots of negative numbers
from scipy import sqrt,integrate
#nullcline
# import PyDSTool as dst
# from PyDSTool.Toolbox import phaseplane as pp
# from PyDSTool import args
# to display plots in-line
%matplotlib inline


#import sympy for fixed points?
import sympy as sm

#widget
from ipywidgets import interact, interactive
from IPython.display import clear_output, display, HTML
from mpl_toolkits.mplot3d import Axes3D
from matplotlib.colors import cnames
from matplotlib import animation

In [3]:
x=[[1,2,3],[4,5,6]]
y=[[2,4,8],[3,6,9],[20,21,22]]
z=[1,2,3,4,5,6,7,8,9,10,11,12]
a=[[z[1]],z[2:4]]
b=[[0,2],[3,4]]
c=[[0,4],[18,24]]

abcd=np.random.rand(10, 5)
print(abcd)

[[ 0.06254078  0.36974009  0.12481706  0.52781628  0.736537  ]
 [ 0.03400535  0.50025358  0.03649624  0.45812727  0.02253294]
 [ 0.64709117  0.70042947  0.40281029  0.91335633  0.17976547]
 [ 0.93413267  0.56259466  0.77597407  0.18497762  0.1675662 ]
 [ 0.21269935  0.23723721  0.62180316  0.87875428  0.18349517]
 [ 0.82623218  0.51600038  0.53430255  0.33479807  0.94800312]
 [ 0.67377041  0.34673655  0.94827641  0.89036906  0.26173615]
 [ 0.25568941  0.84260909  0.22923026  0.85200816  0.24849758]
 [ 0.14330411  0.92437982  0.2644389   0.42153528  0.63211554]
 [ 0.85573384  0.10183727  0.99968213  0.08682684  0.54418884]]
